# Generated by Django 4.2.dev20221010114310 on 2023-02-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_destination', models.CharField(max_length=140)),
                ('text_origin', models.CharField(max_length=140)),
                ('text_date', models.DateField()),
                ('text_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PostOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_destination', models.CharField(max_length=140)),
                ('text_origin', models.CharField(max_length=140)),
                ('text_date', models.DateField()),
                ('text_time', models.TimeField()),
            ],
        ),
    ]
